export const seedHospitals = [
  {
    name: 'Metro Apex Trauma Institute',
    type: 'Level 1 Trauma Center',
    location: { latitude: 12.9716, longitude: 77.5946, address: 'Central Metro Corridor, Zone 1' },
    erBedsTotal: 35,
    erBedsAvailable: 8,
    icuBedsTotal: 24,
    icuBedsAvailable: 6,
    specialtiesAvailable: ['Trauma_Surgery', 'Orthopedics', 'Critical_Care', 'Neurosurgery', 'Cardiology', 'Cath_Lab'],
    activeFacilities: ['Trauma_Bay_1', 'Trauma_Bay_2', 'Cath_Lab', 'CT_Scan', 'MRI_3T', 'OR_Emergency'],
    diversionStatus: false,
    averageWaitTimeMinutes: 8,
    contactPhone: '+91-80-2211-0001',
  },
  {
    name: 'St. Jude Memorial Hospital',
    type: 'Multi-Specialty Apex',
    location: { latitude: 12.9550, longitude: 77.5830, address: 'South District Boulevard' },
    erBedsTotal: 26,
    erBedsAvailable: 1, // High saturation!
    icuBedsTotal: 14,
    icuBedsAvailable: 0, // 0 ICU Beds -> Saturated / Diversion Risk!
    specialtiesAvailable: ['Cardiology', 'General_Surgery', 'Pulmonology'],
    activeFacilities: ['CT_Scan', 'ER_General'],
    diversionStatus: true,
    averageWaitTimeMinutes: 45,
    contactPhone: '+91-80-2211-0002',
  },
  {
    name: 'City Heart & Vascular Institute',
    type: 'Cardiac & Stroke Center',
    location: { latitude: 12.9352, longitude: 77.6245, address: 'Koramangala Tech Ring' },
    erBedsTotal: 22,
    erBedsAvailable: 7,
    icuBedsTotal: 18,
    icuBedsAvailable: 5,
    specialtiesAvailable: ['Cardiology', 'Cath_Lab', 'Neurology', 'Stroke_Unit', 'Interventional_Neuroradiology', 'Critical_Care'],
    activeFacilities: ['Cath_Lab_1', 'Cath_Lab_2', 'Angio_Suite', 'Stroke_Bay', 'CT_Scan'],
    diversionStatus: false,
    averageWaitTimeMinutes: 5,
    contactPhone: '+91-80-2211-0003',
  },
  {
    name: 'Childrens Apex Institute',
    type: 'Pediatric Institute',
    location: { latitude: 12.9902, longitude: 77.5710, address: 'Malleshwaram Healthcare Park' },
    erBedsTotal: 18,
    erBedsAvailable: 9,
    icuBedsTotal: 12,
    icuBedsAvailable: 4,
    specialtiesAvailable: ['Pediatrics', 'Pediatric_Surgery', 'Neonatology', 'Critical_Care'],
    activeFacilities: ['PICU', 'NICU', 'Pediatric_Trauma_Bay'],
    diversionStatus: false,
    averageWaitTimeMinutes: 10,
    contactPhone: '+91-80-2211-0004',
  },
  {
    name: 'Westside General Hospital',
    type: 'Community Hospital',
    location: { latitude: 12.9810, longitude: 77.5360, address: 'Rajajinagar Link Road' },
    erBedsTotal: 16,
    erBedsAvailable: 4,
    icuBedsTotal: 8,
    icuBedsAvailable: 2,
    specialtiesAvailable: ['General_Surgery', 'Orthopedics', 'Internal_Medicine'],
    activeFacilities: ['X_Ray', 'ER_General', 'CT_Scan'],
    diversionStatus: false,
    averageWaitTimeMinutes: 20,
    contactPhone: '+91-80-2211-0005',
  },
  {
    name: 'East Metro Emergency Hospital',
    type: 'Level 1 Trauma Center',
    location: { latitude: 12.9780, longitude: 77.6430, address: 'Indiranagar 100ft Road' },
    erBedsTotal: 30,
    erBedsAvailable: 11,
    icuBedsTotal: 20,
    icuBedsAvailable: 7,
    specialtiesAvailable: ['Trauma_Surgery', 'Orthopedics', 'Critical_Care', 'Cardiology', 'Pulmonology'],
    activeFacilities: ['Trauma_Bay_1', 'OR_Emergency', 'CT_Scan', 'Blood_Bank'],
    diversionStatus: false,
    averageWaitTimeMinutes: 12,
    contactPhone: '+91-80-2211-0006',
  },
  {
    name: 'Greenfield Suburban Clinic',
    type: 'Community Hospital',
    location: { latitude: 13.0120, longitude: 77.6150, address: 'Hebbal Flyover Junction' },
    erBedsTotal: 10,
    erBedsAvailable: 5,
    icuBedsTotal: 4,
    icuBedsAvailable: 1,
    specialtiesAvailable: ['General_Medicine', 'First_Aid'],
    activeFacilities: ['X_Ray', 'Triage_Room'],
    diversionStatus: false,
    averageWaitTimeMinutes: 15,
    contactPhone: '+91-80-2211-0007',
  },
  {
    name: 'North Burn & Specialty Care',
    type: 'Level 1 Trauma Center',
    location: { latitude: 13.0280, longitude: 77.5680, address: 'Yeshwantpur Medical Complex' },
    erBedsTotal: 24,
    erBedsAvailable: 8,
    icuBedsTotal: 16,
    icuBedsAvailable: 5,
    specialtiesAvailable: ['Burn_Unit', 'Trauma_Surgery', 'Plastic_Surgery', 'Critical_Care'],
    activeFacilities: ['Hyperbaric_Bay', 'Burn_ICU', 'OR_Emergency'],
    diversionStatus: false,
    averageWaitTimeMinutes: 10,
    contactPhone: '+91-80-2211-0008',
  },
];

function makeRoute(startLat, startLon, midLat, midLon, endLat, endLon) {
  const pts = [];
  const n = 12;
  for (let i = 0; i <= n; i++) {
    const t = i / n;
    pts.push({
      latitude: parseFloat((startLat + (midLat - startLat) * t + Math.sin(t * Math.PI) * 0.002).toFixed(6)),
      longitude: parseFloat((startLon + (midLon - startLon) * t).toFixed(6)),
    });
  }
  for (let i = 1; i <= n; i++) {
    const t = i / n;
    pts.push({
      latitude: parseFloat((midLat + (endLat - midLat) * t - Math.sin(t * Math.PI) * 0.002).toFixed(6)),
      longitude: parseFloat((midLon + (endLon - midLon) * t).toFixed(6)),
    });
  }
  return pts;
}

export const seedAmbulances = [
  {
    callSign: 'AMB-01 (ALS)',
    vehicleNumber: 'KA-01-EA-1081',
    ambulanceType: 'ALS',
    location: { latitude: 12.9650, longitude: 77.5850, heading: 45, speedKmH: 48 },
    status: 'En_Route_Scene',
    currentIncidentId: 'INC-2026-901',
    targetHospitalId: 'HOSP-3',
    activeRoute: makeRoute(12.9650, 77.5850, 12.9690, 77.5990, 12.9352, 77.6245),
    routeProgressIndex: 3,
    equipment: ['Defibrillator', '12-Lead ECG', 'Oxygen_Supply', 'Suction', 'IV_Infusion', 'Immobilization_Kit'],
    paramedicCrew: { leadParamedic: 'Ramesh K., Paramedic Specialist', skillLevel: 'Advanced', crewCount: 2 },
    trafficDelayFactor: 1.05,
    fuelPercent: 94,
  },
  {
    callSign: 'AMB-02 (MICU)',
    vehicleNumber: 'KA-01-EA-1082',
    ambulanceType: 'MICU',
    location: { latitude: 12.9750, longitude: 77.6020, heading: 90, speedKmH: 52 },
    status: 'En_Route_Hospital',
    currentIncidentId: 'INC-2026-902',
    targetHospitalId: 'HOSP-1',
    activeRoute: makeRoute(12.9750, 77.6210, 12.9730, 77.6080, 12.9716, 77.5946),
    routeProgressIndex: 8,
    equipment: ['Ventilator', 'Defibrillator', '12-Lead ECG', 'Suction', 'IV_Infusion', 'Immobilization_Kit', 'Syringe_Pump'],
    paramedicCrew: { leadParamedic: 'Dr. Priya Sharma, Emergency Physician', skillLevel: 'Doctor', crewCount: 3 },
    trafficDelayFactor: 1.0,
    fuelPercent: 88,
  },
  {
    callSign: 'AMB-03 (BLS)',
    vehicleNumber: 'KA-01-EA-1083',
    ambulanceType: 'BLS',
    location: { latitude: 12.9680, longitude: 77.5920, heading: 180, speedKmH: 40 },
    status: 'Available',
    equipment: ['Oxygen_Supply', 'First_Aid_Kit', 'Splints', 'Stretcher'],
    paramedicCrew: { leadParamedic: 'Arun V., EMT-Basic', skillLevel: 'Basic', crewCount: 2 },
    trafficDelayFactor: 1.0,
    fuelPercent: 96,
  },
  {
    callSign: 'AMB-04 (PALS)',
    vehicleNumber: 'KA-01-EA-1084',
    ambulanceType: 'PALS',
    location: { latitude: 12.9850, longitude: 77.5750, heading: 270, speedKmH: 46 },
    status: 'Available',
    equipment: ['Pediatric_Kit', 'Ventilator', 'Defibrillator', 'Oxygen_Supply', 'Suction', 'Neonatal_Warmer'],
    paramedicCrew: { leadParamedic: 'Meena R., Pediatric Paramedic', skillLevel: 'Advanced', crewCount: 2 },
    trafficDelayFactor: 1.1,
    fuelPercent: 82,
  },
  {
    callSign: 'AMB-05 (MICU)',
    vehicleNumber: 'KA-01-EA-1085',
    ambulanceType: 'MICU',
    location: { latitude: 12.9420, longitude: 77.6180, heading: 60, speedKmH: 50 },
    status: 'Available',
    equipment: ['Ventilator', 'Defibrillator', '12-Lead ECG', 'Suction', 'IV_Infusion', 'Trauma_Pack'],
    paramedicCrew: { leadParamedic: 'Vikram S., Critical Care Specialist', skillLevel: 'Critical_Care', crewCount: 3 },
    trafficDelayFactor: 1.0,
    fuelPercent: 91,
  },
  {
    callSign: 'AMB-06 (ALS)',
    vehicleNumber: 'KA-01-EA-1086',
    ambulanceType: 'ALS',
    location: { latitude: 12.9820, longitude: 77.6350, heading: 120, speedKmH: 45 },
    status: 'Available',
    equipment: ['Defibrillator', '12-Lead ECG', 'Oxygen_Supply', 'Suction', 'Trauma_Pack', 'Immobilization_Kit'],
    paramedicCrew: { leadParamedic: 'Karthik N., Advanced EMT', skillLevel: 'Advanced', crewCount: 2 },
    trafficDelayFactor: 1.15,
    fuelPercent: 85,
  },
  {
    callSign: 'AMB-07 (BLS)',
    vehicleNumber: 'KA-01-EA-1087',
    ambulanceType: 'BLS',
    location: { latitude: 12.9510, longitude: 77.5620, heading: 300, speedKmH: 42 },
    status: 'Available',
    equipment: ['Oxygen_Supply', 'First_Aid_Kit', 'Splints', 'Stretcher'],
    paramedicCrew: { leadParamedic: 'Suresh B., EMT-Basic', skillLevel: 'Basic', crewCount: 2 },
    trafficDelayFactor: 1.0,
    fuelPercent: 78,
  },
  {
    callSign: 'AMB-08 (ALS)',
    vehicleNumber: 'KA-01-EA-1088',
    ambulanceType: 'ALS',
    location: { latitude: 13.0150, longitude: 77.6050, heading: 0, speedKmH: 54 },
    status: 'Available',
    equipment: ['Defibrillator', '12-Lead ECG', 'Oxygen_Supply', 'Suction', 'Burn_Kit', 'IV_Infusion'],
    paramedicCrew: { leadParamedic: 'Deepak M., Critical Care Paramedic', skillLevel: 'Critical_Care', crewCount: 2 },
    trafficDelayFactor: 1.0,
    fuelPercent: 95,
  },
];

export const seedIncidents = [
  {
    incidentCode: 'INC-2026-901',
    callerName: 'Sunil Kumar (Passerby)',
    callerPhone: '+91-98765-43210',
    source: 'Bystander_SOS',
    location: { latitude: 12.9690, longitude: 77.5990, address: 'MG Road Metro Station Entry, Bengaluru' },
    chiefComplaint: 'Sudden collapse on sidewalk, clutching chest, sweating profusely, cold skin',
    symptoms: ['crushing chest pain', 'shortness of breath', 'cold sweat', 'dizziness'],
    conscious: true,
    breathing: true,
    severeBleeding: false,
    casualtyCount: 1,
    sceneHazards: ['Traffic'],
    vitals: { heartRate: 134, spo2: 90, systolicBp: 86, diastolicBp: 52, respiratoryRate: 26, gcs: 14, temperature: 36.4 },
    triage: {
      esiLevel: 2,
      triageColor: 'Orange',
      categoryName: 'Emergent (High Risk / Potential Threat)',
      severityScore: 84.0,
      recommendedSpecialties: ['Cardiology', 'Cath_Lab'],
      requiredEquipment: ['12-Lead ECG', 'Defibrillator', 'Oxygen_Supply'],
      minParamedicSkill: 'Advanced',
      firstAidGuidanceKey: 'chest_pain',
      clinicalFlags: ['Suspected Acute Coronary Syndrome / STEMI', 'Hypotension'],
      explanation: 'Critical cardiac symptoms with hypotension and tachycardia require emergency cath lab routing.',
      engine: 'ai_optimized',
    },
    assignedAmbulance: {
      ambulanceId: 'AMB-1',
      callSign: 'AMB-01 (ALS)',
      dispatchedAt: new Date(),
      estimatedArrivalMinutes: 4.5,
      allocationScore: 93.4,
      allocationRationale: 'Selected AMB-01 (ALS) with 12-Lead ECG, Defibrillator, and Advanced Paramedic team.',
    },
    targetHospital: {
      hospitalId: 'HOSP-3',
      name: 'City Heart & Vascular Institute',
      bedReserved: true,
      estimatedArrivalMinutes: 7.2,
      recommendationScore: 96.0,
      recommendationRationale: 'Cardiac & Stroke Center with active Cath Lab and verified ICU beds.',
    },
    status: 'Dispatched',
  },
  {
    incidentCode: 'INC-2026-902',
    callerName: 'Traffic Police Patrol #12',
    callerPhone: '+91-80-2294-2222',
    source: 'Emergency_Call',
    location: { latitude: 12.9750, longitude: 77.6210, address: 'Old Airport Road, Near Domlur Flyover' },
    chiefComplaint: 'Motorcycle collision with delivery truck, open femur fracture, heavy arterial spurting',
    symptoms: ['massive bleeding', 'open fracture', 'severe pain', 'pale skin'],
    conscious: true,
    breathing: true,
    severeBleeding: true,
    casualtyCount: 1,
    sceneHazards: ['Traffic', 'Fuel Spill'],
    vitals: { heartRate: 142, spo2: 94, systolicBp: 80, diastolicBp: 48, respiratoryRate: 28, gcs: 13, temperature: 36.1 },
    triage: {
      esiLevel: 1,
      triageColor: 'Red',
      categoryName: 'Resuscitation (Immediate Life Threat)',
      severityScore: 94.0,
      recommendedSpecialties: ['Trauma_Surgery', 'Orthopedics', 'Critical_Care'],
      requiredEquipment: ['Immobilization_Kit', 'Trauma_Pack', 'Suction', 'IV_Infusion'],
      minParamedicSkill: 'Advanced',
      firstAidGuidanceKey: 'severe_bleeding',
      clinicalFlags: ['Active Severe Hemorrhage', 'Hemorrhagic Shock Risk'],
      explanation: 'Major polytrauma with arterial bleeding requires immediate hemorrhage control and trauma surgical bay.',
      engine: 'ai_optimized',
    },
    assignedAmbulance: {
      ambulanceId: 'AMB-2',
      callSign: 'AMB-02 (MICU)',
      dispatchedAt: new Date(),
      estimatedArrivalMinutes: 3.8,
      allocationScore: 96.2,
      allocationRationale: 'MICU equipped with ventilator, suction, trauma pack, and Emergency Physician on board.',
    },
    targetHospital: {
      hospitalId: 'HOSP-1',
      name: 'Metro Apex Trauma Institute',
      bedReserved: true,
      estimatedArrivalMinutes: 5.5,
      recommendationScore: 98.0,
      recommendationRationale: 'Level 1 Trauma Center with available trauma bays and on-duty surgical teams.',
    },
    status: 'En_Route_Hospital',
  },
];
